### PR TITLE
Feature/issue-01/init-source-code

### LINKED ISSUE #1: [BO] Setup BackOffice repo

### PR DESCRIPTION
**Pull request by quyn2904**

### CODE REVIEW

**Comment by nnh53** [comment]
@quyn2904 please make this repo have convention, wait for me to done my task, i will help u

**Comment by quyn2904** [comment]
transfer to @nnh53

**Comment by nnh53** [comment]
@minhhy2801 Could you please take a moment to review my PR when you have a chance. Thank you for your time and consideration.

**Comment by nnh53** [comment]
Bug Report: Cannot get PostCSS to work @quyn2904 
How to re-create
1. clone repo
2. yarn install 
3. yarn dev

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: F:/1.PROJECT/NikeCloneTraining-FE-BackOffice): [Error] Must use import to load ES Module: F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\postcss.config.ts 
require() of ES modules is not supported.
require() of F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\postcss.config.ts from F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\node_modules\vite\dist\node\chunks\dep-BKbDVx1T.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\package.json.

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\postcss.config.ts
require() of ES modules is not supported.
require() of F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\postcss.config.ts from F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\node_modules\vite\dist\node\chunks\dep-BKbDVx1T.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\package.json.

    at createErrRequireEsm (F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\node_modules\ts-node\dist-raw\node-internal-errors.js:46:15)
    at assertScriptCanLoadAsCJSImpl (F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\node_modules\ts-node\dist-raw\node-internal-modules-cjs-loader.js:584:11)
    at Object.require.extensions.<computed> [as .ts] (F:\1.PROJECT\NikeCloneTraining-FE-BackOffice\node_modules\ts-node\src\index.ts:1610:5)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at file:///F:/1.PROJECT/NikeCloneTraining-FE-BackOffice/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:29311:16
    at Object.search (file:///F:/1.PROJECT/NikeCloneTraining-FE-BackOffice/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:21515:48)] {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.

image

**Comment by nnh53** [comment]
@minhhy2801 Could you please take a moment to review my PR when you have a chance. Thank you for your time and consideration.

**Review by minhhy2801 — APPROVED** [review]

**Pull request merged**
